### ISSUE TITLE
Provide docker-compose.yml in README.md

### ISSUE THREAD

**Issue by petre-c** [fredliang44/derper-docker#13]
Please add docker compose sample in README.md

```yml
services:
    derper:
        environment:
            - DERP_DOMAIN=derper.yourdomain.com # change with your derper domain
        ports:
            - 80:80
            - 443:443
            - 3478:3478/udp
        image: fredliang/derper
        restart: unless-stopped

```
